apiVersion: v1
data:
  key: =
kind: Secret
metadata:
  name: hz-license-key-secret
  labels:
    app.kubernetes.io/name: "HazelcastIMDG-license"    
    app.kubernetes.io/version: "4.0.1"
    app.kubernetes.io/managed-by: isp-managed
    app.kubernetes.io/component: cluster
    app.kubernetes.io/part-of: paascache
    app-type: HazelcastIMDG-license